# -*- coding: utf-8 -*-
"""game_with_110 2026-04-08 10_48_42.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CVHl1dJPILT523AQ7PEjH5rkDx-Kcs7R
"""

df=spark.read.csv("s3://flight-analytics-de-divyansh-2026/bts_flight_data",header=True)
display(df)



from pyspark.sql.types import (
    StructType, StructField,
    StringType, IntegerType, DoubleType, DateType
)

fl_schema = StructType([

    StructField("Year", IntegerType(), True),
    StructField("Quarter", IntegerType(), True),
    StructField("Month", IntegerType(), True),
    StructField("DayofMonth", IntegerType(), True),
    StructField("DayOfWeek", IntegerType(), True),
    StructField("FlightDate", DateType(), True),

    StructField("Reporting_Airline", StringType(), True),
    StructField("DOT_ID_Reporting_Airline", IntegerType(), True),
    StructField("IATA_CODE_Reporting_Airline", StringType(), True),
    StructField("Tail_Number", StringType(), True),
    StructField("Flight_Number_Reporting_Airline", IntegerType(), True),

    StructField("OriginAirportID", IntegerType(), True),
    StructField("OriginAirportSeqID", IntegerType(), True),
    StructField("OriginCityMarketID", IntegerType(), True),
    StructField("Origin", StringType(), True),
    StructField("OriginCityName", StringType(), True),
    StructField("OriginState", StringType(), True),
    StructField("OriginStateFips", IntegerType(), True),
    StructField("OriginStateName", StringType(), True),
    StructField("OriginWac", IntegerType(), True),

    StructField("DestAirportID", IntegerType(), True),
    StructField("DestAirportSeqID", IntegerType(), True),
    StructField("DestCityMarketID", IntegerType(), True),
    StructField("Dest", StringType(), True),
    StructField("DestCityName", StringType(), True),
    StructField("DestState", StringType(), True),
    StructField("DestStateFips", IntegerType(), True),
    StructField("DestStateName", StringType(), True),
    StructField("DestWac", IntegerType(), True),

    StructField("CRSDepTime", IntegerType(), True),
    StructField("DepTime", IntegerType(), True),
    StructField("DepDelay", DoubleType(), True),
    StructField("DepDelayMinutes", DoubleType(), True),
    StructField("DepDel15", DoubleType(), True),
    StructField("DepartureDelayGroups", IntegerType(), True),
    StructField("DepTimeBlk", StringType(), True),

    StructField("TaxiOut", DoubleType(), True),
    StructField("WheelsOff", IntegerType(), True),
    StructField("WheelsOn", IntegerType(), True),
    StructField("TaxiIn", DoubleType(), True),

    StructField("CRSArrTime", IntegerType(), True),
    StructField("ArrTime", IntegerType(), True),
    StructField("ArrDelay", DoubleType(), True),
    StructField("ArrDelayMinutes", DoubleType(), True),
    StructField("ArrDel15", DoubleType(), True),
    StructField("ArrivalDelayGroups", IntegerType(), True),
    StructField("ArrTimeBlk", StringType(), True),

    StructField("Cancelled", DoubleType(), True),
    StructField("CancellationCode", StringType(), True),
    StructField("Diverted", DoubleType(), True),

    StructField("CRSElapsedTime", DoubleType(), True),
    StructField("ActualElapsedTime", DoubleType(), True),
    StructField("AirTime", DoubleType(), True),
    StructField("Flights", DoubleType(), True),
    StructField("Distance", DoubleType(), True),
    StructField("DistanceGroup", IntegerType(), True),

    StructField("CarrierDelay", DoubleType(), True),
    StructField("WeatherDelay", DoubleType(), True),
    StructField("NASDelay", DoubleType(), True),
    StructField("SecurityDelay", DoubleType(), True),
    StructField("LateAircraftDelay", DoubleType(), True),

    StructField("FirstDepTime", IntegerType(), True),
    StructField("TotalAddGTime", DoubleType(), True),
    StructField("LongestAddGTime", DoubleType(), True),

    StructField("DivAirportLandings", DoubleType(), True),
    StructField("DivReachedDest", DoubleType(), True),
    StructField("DivActualElapsedTime", DoubleType(), True),
    StructField("DivArrDelay", DoubleType(), True),
    StructField("DivDistance", DoubleType(), True),

    StructField("Div1Airport", StringType(), True),
    StructField("Div1AirportID", IntegerType(), True),
    StructField("Div1AirportSeqID", IntegerType(), True),
    StructField("Div1WheelsOn", IntegerType(), True),
    StructField("Div1TotalGTime", DoubleType(), True),
    StructField("Div1LongestGTime", DoubleType(), True),
    StructField("Div1WheelsOff", IntegerType(), True),
    StructField("Div1TailNum", StringType(), True),

    StructField("Div2Airport", StringType(), True),
    StructField("Div2AirportID", IntegerType(), True),
    StructField("Div2AirportSeqID", IntegerType(), True),
    StructField("Div2WheelsOn", IntegerType(), True),
    StructField("Div2TotalGTime", DoubleType(), True),
    StructField("Div2LongestGTime", DoubleType(), True),
    StructField("Div2WheelsOff", IntegerType(), True),
    StructField("Div2TailNum", StringType(), True),

    StructField("Div3Airport", StringType(), True),
    StructField("Div3AirportID", IntegerType(), True),
    StructField("Div3AirportSeqID", IntegerType(), True),
    StructField("Div3WheelsOn", IntegerType(), True),
    StructField("Div3TotalGTime", DoubleType(), True),
    StructField("Div3LongestGTime", DoubleType(), True),
    StructField("Div3WheelsOff", IntegerType(), True),
    StructField("Div3TailNum", StringType(), True),

    StructField("Div4Airport", StringType(), True),
    StructField("Div4AirportID", IntegerType(), True),
    StructField("Div4AirportSeqID", IntegerType(), True),
    StructField("Div4WheelsOn", IntegerType(), True),
    StructField("Div4TotalGTime", DoubleType(), True),
    StructField("Div4LongestGTime", DoubleType(), True),
    StructField("Div4WheelsOff", IntegerType(), True),
    StructField("Div4TailNum", StringType(), True),

    StructField("Div5Airport", StringType(), True),
    StructField("Div5AirportID", IntegerType(), True),
    StructField("Div5AirportSeqID", IntegerType(), True),
    StructField("Div5WheelsOn", IntegerType(), True),
    StructField("Div5TotalGTime", DoubleType(), True),
    StructField("Div5LongestGTime", DoubleType(), True),
    StructField("Div5WheelsOff", IntegerType(), True),
    StructField("Div5TailNum", StringType(), True),

    StructField("_c109", StringType(), True),
    StructField("_currupt_record",StringType(),True)
])

df = spark.read.format("csv")\
    .option("header", True)\
    .schema(fl_schema)\
    .load("s3://flight-analytics-de-divyansh-2026/bts_flight_data/*/*/")
display(df)

df= spark.read \
    .option("header", True) \
    .option("nullValue","") \
    .option("emptyValue","") \
    .schema(fl_schema) \
    .csv("s3://flight-analytics-de-divyansh-2026/bts_flight_data/")
display(df)

df.select("year", "month").distinct().orderBy("year", "month").display()

df_2022= spark.read \
    .option("header", True) \
    .schema(fl_schema) \
    .csv("s3://flight-analytics-de-divyansh-2026/bts_flight_data/")
display(df_2022)

df_permissive = spark.read.format("csv") \
    .option("header", "true") \
    .option("nullValue", "") \
    .option("emptyValue", "") \
    .option("mode", "PERMISSIVE") \
    .schema(fl_schema) \
    .load("s3://flight-analytics-de-divyansh-2026/bts_flight_data/")

display(df_permissive)

total_count=df_permissive.count()
print(f"Total count of records in the dataset is {total_count}")

df_dropmalformed = spark.read.format("csv") \
    .option("header", "true") \
    .option("nullValue", "") \
    .option("emptyValue", "") \
    .option("mode", "DROPMALFORMED") \
    .schema(fl_schema) \
    .load("s3://flight-analytics-de-divyansh-2026/bts_flight_data/")


display(df_dropmalformed)

total_count=df_dropmalformed.count()
print(f"Total count of records in the dataset is {total_count}")

df_failfast = spark.read.format("csv") \
    .option("header", "true") \
    .option("nullValue", "") \
    .option("emptyValue", "") \
    .option("mode", "FAILFAST") \
    .schema(fl_schema) \
    .load("s3://flight-analytics-de-divyansh-2026/bts_flight_data/*/*/")


display(df_failfast)

final_df = spark.read.format("csv") \
    .option("header", "true") \
    .option("nullValue", "") \
    .option("emptyValue", "") \
    .option("mode", "PERMISSIVE") \
    .load("s3://flight-analytics-de-divyansh-2026/bts_flight_data/")

display(final_df)

from pyspark.sql.functions import current_timestamp, col

df_bronze = final_df.withColumn("ingestion_time", current_timestamp()) \
                    .withColumn("source_file_name", col("_metadata.file_path"))

display(df_bronze)

total_records = df_bronze.count()
print("Total number of records:", total_records)

from pyspark.sql.functions import col

flightdate_null_count = df_bronze.filter(col("FlightDate").isNull()).count()

print("FlightDate null count:", flightdate_null_count)

from pyspark.sql.functions import col, when, sum as spark_sum

# Total records
total_records = df_bronze.count()

# FlightDate column select karke null ko 1 and non-null ko 0
flightdate_null_count = df_bronze.select(
    when(col("FlightDate").cast("string").isNull(), 1).otherwise(0).alias("itsnull")
).agg(
    spark_sum("itsnull").alias("null_count")
).collect()[0]["null_count"]

# Null percentage
flightdate_null_percentage = (flightdate_null_count / total_records) * 100

print("Total Records:", total_records)
print("FlightDate Null Count:", flightdate_null_count)
print("FlightDate Null Percentage:", round(flightdate_null_percentage, 2), "%")

from pyspark.sql.functions import col, when, sum as spark_sum

# Total records
total_records = df_bronze.count()

# FlightDate column select karke null ko 1 and non-null ko 0
flightdate_null_count = df_bronze.select(
    when(col("distance").cast("string").isNull(), 1).otherwise(0).alias("itsnull")
).agg(
    spark_sum("itsnull").alias("null_count")
).collect()[0]["null_count"]

# Null percentage
flightdate_null_percentage = (flightdate_null_count / total_records) * 100

print("Total Records:", total_records)
print("FlightDate Null Count:", flightdate_null_count)
print("FlightDate Null Percentage:", round(flightdate_null_percentage, 2), "%")

from pyspark.sql.functions import col, when, sum as spark_sum

# Total records
total_records = df_bronze.count()

# FlightDate column select karke null ko 1 and non-null ko 0
flightdate_null_count = df_bronze.select(
    when(col("ArrDelay").cast("string").isNull(), 1).otherwise(0).alias("itsnull")
).agg(
    spark_sum("itsnull").alias("null_count")
).collect()[0]["null_count"]

# Null percentage
flightdate_null_percentage = (flightdate_null_count / total_records) * 100

print("Total Records:", total_records)
print("FlightDate Null Count:", flightdate_null_count)
print("FlightDate Null Percentage:", round(flightdate_null_percentage, 2), "%")

from pyspark.sql.functions import col, when, sum as spark_sum

# Total records
total_records = df_bronze.count()

# FlightDate column select karke null ko 1 and non-null ko 0
flightdate_null_count = df_bronze.select(
    when(col("dep_delay").cast("string").isNull(), 1).otherwise(0).alias("itsnull")
).agg(
    spark_sum("itsnull").alias("null_count")
).collect()[0]["null_count"]

# Null percentage
flightdate_null_percentage = (flightdate_null_count / total_records) * 100

print("Total Records:", total_records)
print("FlightDate Null Count:", flightdate_null_count)
print("FlightDate Null Percentage:", round(flightdate_null_percentage, 2), "%")

from pyspark.sql.functions import col, when, sum as spark_sum

total_records = df_bronze.count()

flightdate_null_count = df_bronze.select(
    when(col("reporting_airline").cast("string").isNull(), 1).otherwise(0).alias("itsnull")
).agg(
    spark_sum("itsnull").alias("null_count")
).collect()[0]["null_count"]

# -------- null percentage -----------#
flightdate_null_percentage = (flightdate_null_count / total_records) * 100

print("Total Records:", total_records)
print("FlightDate Null Count:", flightdate_null_count)
print("FlightDate Null Percentage:", round(flightdate_null_percentage, 2), "%")

from pyspark.sql.functions import min, max , month , year

df_bronze.select(
min("FlightDate").alias("min_date"),
max("FlightDate").alias("max_date"),
min(year("FlightDate")).alias("min year"),
max(year("FlightDate")).alias("max year"),
min(month("FlightDate")). alias("min_month"),
max(month("FlightDate")).alias("max_month")
).show()

df_bronze.columns()