# -*- coding: utf-8 -*-
"""game_with_35 2026-04-10 12_04_14 (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iouKw8PFsHlodf8TKVRlicdPRP9YwLFy
"""

spark.sql("""
CREATE OR REPLACE TEMP VIEW tb1
USING csv
OPTIONS (
  path "s3://flight-analytics-de-divyansh-2026/bts_flight_data/*/*/",
  header "true"
)
""")

df=spark.sql("select * from tb1")

display(df)
df.columns

from pyspark.sql.functions import col, when, concat_ws

# Step 1: Full read with PERMISSIVE
df_full = spark.read.format("csv") \
    .option("header", True) \
    .option("mode", "PERMISSIVE") \
    .option("nullValue", "") \
    .option("emptyValue", "") \
    .load("s3://flight-analytics-de-divyansh-2026/bts_flight_data/")

# Step 2: Required 35 columns only
df_req = df_full.select(
    col("FlightDate").cast("string").alias("FlightDate"),
    col("Reporting_Airline").cast("string").alias("Reporting_Airline"),
    col("IATA_CODE_Reporting_Airline").cast("string").alias("IATA_CODE_Reporting_Airline"),
    col("Tail_Number").cast("string").alias("Tail_Number"),
    col("Flight_Number_Reporting_Airline").cast("int").alias("Flight_Number_Reporting_Airline"),
    col("Origin").cast("string").alias("Origin"),
    col("OriginCityName").cast("string").alias("OriginCityName"),
    col("OriginState").cast("string").alias("OriginState"),
    col("Dest").cast("string").alias("Dest"),
    col("DestCityName").cast("string").alias("DestCityName"),
    col("DestState").cast("string").alias("DestState"),
    col("CRSDepTime").cast("int").alias("CRSDepTime"),
    col("DepTime").cast("double").alias("DepTime"),
    col("DepDelay").cast("double").alias("DepDelay"),
    col("DepDelayMinutes").cast("double").alias("DepDelayMinutes"),
    col("DepDel15").cast("double").alias("DepDel15"),
    col("DepartureDelayGroups").cast("int").alias("DepartureDelayGroups"),
    col("CRSArrTime").cast("int").alias("CRSArrTime"),
    col("ArrTime").cast("double").alias("ArrTime"),
    col("ArrDelayMinutes").cast("double").alias("ArrDelayMinutes"),
    col("ArrivalDelayGroups").cast("int").alias("ArrivalDelayGroups"),
    col("Cancelled").cast("double").alias("Cancelled"),
    col("CancellationCode").cast("string").alias("CancellationCode"),
    col("Diverted").cast("double").alias("Diverted"),
    col("CRSElapsedTime").cast("double").alias("CRSElapsedTime"),
    col("ActualElapsedTime").cast("double").alias("ActualElapsedTime"),
    col("AirTime").cast("double").alias("AirTime"),
    col("Flights").cast("double").alias("Flights"),
    col("Distance").cast("double").alias("Distance"),
    col("DistanceGroup").cast("int").alias("DistanceGroup"),
    col("CarrierDelay").cast("double").alias("CarrierDelay"),
    col("WeatherDelay").cast("double").alias("WeatherDelay"),
    col("NASDelay").cast("double").alias("NASDelay"),
    col("SecurityDelay").cast("double").alias("SecurityDelay"),
    col("LateAircraftDelay").cast("double").alias("LateAircraftDelay")
)

# Step 3: Separate corrupt dataframe
df_req = df_req.withColumn(
    "_currupt_record_",
    when(
        col("FlightDate").isNull() |
        col("Reporting_Airline").isNull() |
        col("Origin").isNull() |
        col("Dest").isNull() |
        col("CRSDepTime").isNull(),
        concat_ws(",", *[col(c).cast("string") for c in df_req.columns])
    ).otherwise(None)
)

display(df_req)

#df_req.createOrReplaceTempView("flight_35_view")

#df_req.createOrReplaceTempView("flight_35_view")

#display(spark.sql("select * from flight_35_view"))

display(df_req)

from pyspark.sql import functions as f

# Step 1: total count
total_count = df_req.count()

# Step 2: dictionary create
null_dict = {
    "Origin": 0,
    "Cancelled": 0
}

# Step 3: loop on dictionary keys
for key in null_dict.keys():
    null_count = df_req.filter(f.col(key).isNull()).count()
    null_percentage = (null_count / total_count) * 100
    null_dict[key] = null_percentage

# Step 4: print result
print(null_dict)
print(total_count)

from pyspark.sql import functions as f

# Step 1: dictionary create
# key = original column name
# value = null (just for assignment requirement / placeholder)
null_col_dict = {
    "FlightDate": None,
    "Reporting_Airline": None,
    "Origin": None,
    "Dest": None
}

# Step 2: loop through dictionary keys
# Har key ek original dataframe column hai
for key in null_col_dict.keys():

    # Step 3: create new null indicator column
    # Agar column null ya empty hai -> 1
    # Otherwise -> 0
    df_req = df_req.withColumn(
        f"{key}_null",
        f.when(
            f.col(key).isNull() | (f.trim(f.col(key)) == ""),
            1
        ).otherwise(0)
    )

# Step 4: display final dataframe
display(df_req)

from pyspark.sql.functions import col, when

null_cols = {
    "Reporting_Airline": None,
    "FlightDate": None,
    "Origin": None,
    "Dest": None
}

df_req = df_req.withColumns({
    f"null_{c}": when(col(c).isNull(), 1).otherwise(0)
    for c in null_cols.keys()
})

display(df_req)

from pyspark.sql.functions import col, when

null_cols = {
    "Reporting_Airline": None,
    "FlightDate": None,
    "Origin": None,
    "Dest": None
}

for c in null_cols.keys():
    df_req = df_req.withColumn(
        f"null_{c}",
        when(col(c).isNull(), 1).otherwise(0)
    )

display(df_req)

from pyspark.sql.functions import col, when

# final bronze dataframe from original dataframe
df_bronze = df_req

# 1. departure_delay_range
# valid range: -1440 to 1440
# if outside range -> 1 else 0

df_bronze = df_bronze.withColumn(
    "departure_delay_range",
    when(
        (col("DepDelay") < -120) | (col("DepDelay") <= -1440),
        1
    ).otherwise(0)
)

display(df_bronze)

# 2. same_origin_destination
# if Origin == Dest -> 1 else 0
df_bronze = df_bronze.withColumn(
    "same_origin_destination",
    when(
        col("Origin") == col("Dest"),
        1
    ).otherwise(0)
)

# 3. domestic_flights_check_distance_range
# valid domestic distance range: 1 to 10000 km
# if between 1 and 10000 -> 0 else 1
df_bronze = df_bronze.withColumn(
    "domestic_flights_check_distance_range",
    when(
        (col("Distance") >= 1) & (col("Distance") <= 10000),
        0
    ).otherwise(1)
)

# display final bronze dataframe
display(df_bronze)

# 0 wale records (valid distance)
df_bronze.filter(col("domestic_flights_check_distance_range") == 0).display()

# 0 ka count
df_bronze.filter(col("domestic_flights_check_distance_range") == 0).count()

df_bronze.groupBy("domestic_flights_check_distance_range").count().display()

df_bronze.filter(col("Distance") > 10000).count()

# 1.... > create schemna for flight date , reporting airline, iatacode , tailno , flightno reporting ,
# origin , origin city, origin state , destination , dstination city , dest satet,
# cr departurer time , departure time , departure delay , departure delay minutes ,
# dep de 115 , dep delay grolup , cr arrigival time , arrival time , arrival dela mins
# arrival delay roup , cancelled , cancellatio n code , diverted , cr sl elipsed ,
# actual elipsed time , air time , flights , istance , distance group ,
# carrier delay , weather delay , nas delay , security delay , late aircraft

# 2...> header file , mode permissive , column name of corrupt record ,
# null values will  be replaced by empty string , empty value will be replaced by empty string
# _corrupt (condition = if _ corrupt occurs in column then return nul)
# replace it by none if there is no corrupt value.

# 3...> origin , cancelled , store every column in distionary where olumn name is key and vlue is 0
# now loop on every key of dictionary , (f.col--> dictionary key )
# calculate null percentage of these columns as values of keys

# 4...> (airline , flightnight , origin , destination)  >>> .withcolumn and withcolumns ( if flight date null cast it to integer ,means if null ->1,, bakiyo ko 0 ,,,reporting airline = null then  typecast it to null make the final changes like this
# create the colum name as null_column name ,,, columns will be passed as dictionaries and vlaues are null

# for checing and fetting comparision withbteen thiswith column and dictionaries

# 5....> now at the end create the final bronze dataframe

# 5....> original dataframe se make new column departure delay range
# departure delay must be between ( below -2 hours and below 24 hours )
# and its opposite also ~) 1

# 6...> same_origin _destination if both are same then 1 else 0
# 7....> domestic flights (check_distance_range )1_10000 kms if yes then 0 else 1